import { prisma } from '@/lib/prisma'

export type RoundRobinSide = {
  key: string // userId (simples) ou "idA-idB" ordenado (duplas)
  userIds: [string] | [string, string]
}

/** Lados confirmados de um evento Ranking: 1 atleta (simples) ou dupla com parceiro mútuo confirmado. */
export async function buildSides(eventId: string): Promise<RoundRobinSide[]> {
  const event = await prisma.event.findUnique({ where: { id: eventId }, select: { format: true } })
  if (!event) return []

  const confirmed = await prisma.eventRegistration.findMany({
    where: { eventId, status: 'CONFIRMED' },
    select: { userId: true, partnerId: true },
  })

  if (event.format !== 'DOUBLES') {
    return confirmed.map((r) => ({ key: r.userId, userIds: [r.userId] }))
  }

  // Duplas: só forma lado quem tem parceiro também confirmado no evento
  const confirmedIds = new Set(confirmed.map((r) => r.userId))
  const seen = new Set<string>()
  const sides: RoundRobinSide[] = []
  for (const r of confirmed) {
    if (!r.partnerId || !confirmedIds.has(r.partnerId)) continue
    const pair = [r.userId, r.partnerId].sort() as [string, string]
    const key = pair.join('-')
    if (seen.has(key)) continue
    seen.add(key)
    sides.push({ key, userIds: pair })
  }
  return sides
}

function teamKey(ids: (string | null)[]): string {
  return ids.filter((id): id is string => !!id).sort().join('-')
}

/**
 * Gera (se ainda não existirem) todos os confrontos entre os lados confirmados do evento.
 * Idempotente: pode ser chamada de novo (ex: reabriu inscrições, adicionou atleta, fechou de novo)
 * sem duplicar confrontos já existentes. Retorna quantos confrontos novos foram criados.
 */
export async function generateRoundRobinMatches(eventId: string): Promise<number> {
  const sides = await buildSides(eventId)
  if (sides.length < 2) return 0

  const existing = await prisma.match.findMany({
    where: { eventId, status: { not: 'CANCELLED' } },
    select: { player1Id: true, player2Id: true, player3Id: true, player4Id: true },
  })
  const existingKeys = new Set(
    existing.map((m) => [teamKey([m.player1Id, m.player3Id]), teamKey([m.player2Id, m.player4Id])].sort().join('|')),
  )

  const toCreate: { eventId: string; player1Id: string; player2Id: string; player3Id: string | null; player4Id: string | null; status: 'SCHEDULED'; autoGenerated: true }[] = []
  for (let i = 0; i < sides.length; i++) {
    for (let j = i + 1; j < sides.length; j++) {
      const a = sides[i]
      const b = sides[j]
      const matchKey = [a.key, b.key].sort().join('|')
      if (existingKeys.has(matchKey)) continue
      toCreate.push({
        eventId,
        player1Id: a.userIds[0],
        player2Id: b.userIds[0],
        player3Id: a.userIds[1] ?? null,
        player4Id: b.userIds[1] ?? null,
        status: 'SCHEDULED',
        autoGenerated: true,
      })
    }
  }

  if (toCreate.length === 0) return 0
  // createMany em vez de $transaction com um create por linha: com eventos grandes (dezenas de
  // atletas geram centenas de pares) uma transação interativa de N creates estoura o timeout
  // padrão do Prisma (5s). createMany é uma única query, sem esse limite.
  await prisma.match.createMany({ data: toCreate })
  return toCreate.length
}
