-- AlterTable
ALTER TABLE "events" ADD COLUMN "registrationsClosedAt" TIMESTAMP(3);
ALTER TABLE "events" ADD COLUMN "finishedAt" TIMESTAMP(3);
ALTER TABLE "events" ADD COLUMN "closureLog" JSONB;

-- AlterTable
ALTER TABLE "matches" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "matches" ADD COLUMN "isAdminScore" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "matches" ADD COLUMN "resultType" TEXT;
ALTER TABLE "matches" ADD COLUMN "scoreEditedById" TEXT;
ALTER TABLE "matches" ADD COLUMN "scoreEditedAt" TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE "matches" ADD CONSTRAINT "matches_scoreEditedById_fkey" FOREIGN KEY ("scoreEditedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
